const actionTypes = {
    LOAD_USERS:'LOAD_USERS',
    RECEIVE_USERS:'RECEIVE_USERS',
    LOAD_USERS_FAILURE:'LOAD_USERS_FAILURE',
    SELECT_USER: 'SELECT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER'
  };
  
  export default actionTypes;